"""Added Message model

Revision ID: 7e89a78b5966
Revises: 62342d9c87b1
Create Date: 2024-07-05 18:54:53.952033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e89a78b5966'
down_revision = '62342d9c87b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
